import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Head from 'next/head'
import { header } from "@/styles/styles";
import { useAuth } from "@clerk/nextjs";
import TodoItem from "@/components/todo";
import { getTodoById } from "@/modules/Data";

export default function Id(){
    const [todoItem, setTodoItem] = useState(null)
    const [loading, setLoading] = useState(true);
    const router = useRouter();
    const {id} = router.query;
    const { isLoaded, userId, sessionId, getToken } = useAuth();

    useEffect(() => {
        async function process() {
          if (userId) {
            const token = await getToken({ template: "codehooks" });
            const todo = await getTodoById(token, id);
            setTodoItem(todo);
            setLoading(false);
          }
        }
        process();
      }, [isLoaded]);

    if(loading){
        return(<><span>LOADING</span></>);
    } else{
    return (
        <>
          <Head>
            <title>Item {id}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="pure-g">
                <div className="pure-u-1" css={header}>
                    <TodoItem todo={todoItem}></TodoItem>
                </div>
            </div>
        </>
      )
    }
}