/** @jsxImportSource @emotion/react */
import { header } from "@/styles/styles";
import { useState, useEffect } from "react";
import { TodoList } from "@/components/todo";
import Head from 'next/head'
import { useAuth } from "@clerk/nextjs";
import { getTodo } from "@/modules/Data";

export default function Done(){
    const [todoItemList, setTodoItemList] = useState([]);
    const [loading, setLoading] = useState(true);
    const { isLoaded, userId, sessionId, getToken } = useAuth();

    useEffect(() => {
        async function process() {
          if (userId) {
            const token = await getToken({ template: "codehooks" });
            const todoList = await getTodo(token);
            setTodoItemList(todoList.filter(todoItem => todoItem.done));
            setLoading(false);
          }
        }
        process();
      }, [isLoaded]);


    if(loading){
        return(<><span>LOADING</span></>);
    } else{
    return (
        <>
          <Head>
            <title>Todo list home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="pure-g">
                <div className="pure-u-1" css={header}>
                    <h2>Your done items</h2>
                    <TodoList todoItems={todoItemList}></TodoList>
                </div>
            </div>
        </>
      )
    }
}