/** @jsxImportSource @emotion/react */
import { header } from "@/styles/styles";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import {SignedIn, SignedOut, SignInButton, UserButton} from "@clerk/nextjs";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo list home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pure-g">
            <div className="pure-u-1" css={header}>
                <h1>Welcome!</h1>
                <SignedIn>
                {/* Mount the UserButton component */}
                  <UserButton />
                </SignedIn>
                <SignedOut>
                {/* Signed out users get sign in button */}
                  <SignInButton className="pure-button-primary" redirectUrl="/todo"/>
                </SignedOut>
            </div>
        </div>
    </>
  )
}
