/** @jsxImportSource @emotion/react */
import { header } from "@/styles/styles";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import {SignedIn, SignedOut, SignInButton, UserButton, useAuth} from "@clerk/nextjs";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { customButton } from "@/styles/styles";
import { Router } from "next/router";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isSignedIn, userId } = useAuth();
  const router = useRouter();

  //if user visits index page while already logged in, redirect to todo
  useEffect(() => {
    async function process() {
      if (userId) {
        router.push('/todo')
      }
    }
    process();
  }, [userId]);

  return (
    <>
      <Head>
        <title>Todo list home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pure-g">
            <div className="pure-u-1" css={header}>
                <h1>Welcome!</h1>
                <SignedOut>
                  <SignInButton className="pure-button-primary" css={customButton} redirectUrl="/todo"/>
                </SignedOut>
            </div>
        </div>
    </>
  )
}
