/** @jsxImportSource @emotion/react */
import { header } from "@/styles/styles";
import { useState } from "react";
import TodoItem from "@/components/todo";
import { TodoList } from "@/components/todo";
import { TodoBuilder } from "@/components/todo";
import Head from 'next/head'

export default function Todo(){
    let ITEMS = [{content: "complete an item"}, {content: "finish the frontend"}, {content: "finish the backend"}]
    const [todoItemList, setTodoItemList] = useState(ITEMS);

    function handleAdd(content){
        let newList = todoItemList.slice();
        newList.push({content: content});
        setTodoItemList(newList);
    }

    return (
        <>
          <Head>
            <title>Todo list home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className="pure-g">
                <div className="pure-u-1" css={header}>
                    <h2>Your todo list</h2>
                    <TodoList todoItems={todoItemList}></TodoList>
                    <TodoBuilder onAdd={(content) => handleAdd(content)}></TodoBuilder>
                </div>
            </div>
        </>
      )
}